{% set version = "22.0" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 2198ec20bd4c017b8f9717e00f0c8714076fc2fd93816750ab48e2c41de2cfd3

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - flit-core
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - packaging
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_file: LICENSE
  license_family: Apache
  summary: Core utilities for Python packages
  doc_url: https://packaging.pypa.io
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - mingwandroid
