{% set version = "20.0" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: fe1d8331dfa7cc0a883b49d75fc76380b2ab2734b220fbb87d774e4fd4b851f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pyparsing >=2.0.2
    - six

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache 2.0 or BSD 2-Clause
  license_file: LICENSE
  summary: Core utilities for Python packages
  
  description: |
    
  doc_url: https://packaging.pypa.io/en/latest/
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - mingwandroid
