{% set version = "21.0" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 7dc96269f53a4ccec5c0670940a4281106dd0bb343f47b7471f779df49c2fbe7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - python
    - pip
    - flit

  run:
    - python
    - pyparsing >=2.0.2
    - six

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache 2.0 or BSD 2-Clause
  license_file: LICENSE
  summary: Core utilities for Python packages
  
  description: |
    
  doc_url: https://packaging.pypa.io/en/latest/
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - mingwandroid
