{% set version = "23.2" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 048fb0e9405036518eaaf48a55953c750c11e1a1b68e0dd1a9d62ed0c092cfc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation -vv

requirements:
  host:
    - python >=3.7
    - flit >=3.3
    - pip

  run:
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - packaging
  commands:
    - pip check

about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
  dev_url: https://github.com/pypa/packaging
  doc_url: https://github.com/pypa/packaging/tree/main/docs

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for chainlit
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - jakirkham
    - nicoddemus
