{% set version = "20.1" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: e665345f9eef0c621aa0bf2f8d78cf6d21904eef16a93f020240b704a57f1334

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pyparsing >=2.0.2
    - six

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache 2.0 or BSD 2-Clause
  license_file: LICENSE
  summary: Core utilities for Python packages
  
  description: |
    
  doc_url: https://packaging.pypa.io/en/latest/
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - mingwandroid
