travis:
  secure:
    BINSTAR_TOKEN: VXWh0TECfzA7AAbOrcQQjNsCJlUq6hEJ/ZQSfLiGZGNQHARxuJvMqxKIajhQrJDyT0QOIW6tDzYXdObn8fSIknmibeH1fzRGBdxfo/tJaV1NIT8xNykJEBc80ydVSYsJhZrfBwX2rWinvGjxiTrETKtqXe/U/i/eHjK0N4GMLg/9SpjLyWuRAD7WfQf1YGxWHYRvDex0//PSpcT8AMPjGfLQRz15V9ati6XZ/8rJkXnz7dapiu6SogD2BnIfjploEjJ0oMQ38HUUJWmQDu5AcHbwySc160/REDQLzd3V1Qqal5MsSXJeZ8Pg7O1iBpbXXV9SB+xnHXo6CAnKLPlkpXNrzBPtUHqRiP9V1ANu+ofSdFgYfh/6TCwSR8O4rAFOhohR965ujvVS1Z8Ycbdtn1+GqdEzvriszztjv8YKKeACZJQuOWFMQ+TJuQ3dBZmvHhv/i0cgwSFBFSB/nLPk1TzoatbPKVwR8rgAVBDmp6vk+KGn0YfzkjO+4IAJEyTH0ygjtrOifz8g7gsWJMUtDwNNXnMGMgOwZxfLXnJpnqlOjyIuFcMU7sbn0+AisZCbL4TyX3jQge6cuoL7q4QUXWjKd8pmFswPfUcf5vtcNTKokpKI9RcrZP1mwZXUFV/wqf8wN1p5pkvVp/mxDNMV2euFAH4TJnUEp/zF2jMH+OQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
