travis:
  secure:
    BINSTAR_TOKEN: PxXUckE5LB38rj65HqtbE+4mn5gHcx3D81Vy5Db1zpIeQNUa2DzFCMqX/wyPZ7YOJJHk/32kNQyfbrGypOSIIEFUXG3LHpq7jnlXpHcrvTT8tUukOC7rSlKXDUFlRf8tpQvPHwo5SQK51XjG1calOZmJReZZWpjVusE9T+sytoUdwH4WqqYtlvxcx9OxLhj4XvRPv8AZF8tO4d0d/LL9WPdHocRLR3wTOAaLjK+y/8ywIkRxKNPGP0pUxaS8CTX3uMNpQp7/i1TfA9MltD3jiT+0FwS8J4643RkXOD0tKaj+uHw41yMf6+IkQUDXUlghjwdl3nAnrTBbiF+GPnR2He9AebDcBIUujYGuETiVAi+CshTRVrRC1Hdq33aqk0i2U6hYJLXJpmN3SV7PBh8Vf6K91KkLEdG/LSR4oqkpTKUDUsCwRCLbbU8ztT8dYR1aSpYt4d+VukQz9L29ED1sZzThSWoOX/x+njt5/M+edF10eXj10MThOIJAVpY0stJV/3jvydVty1DUKOubM4RcjWvCbKIad4nSinIgP2ytdoxq3HkpCBdpAR7yqmvc7fNZK9Yb1XVTuUlAfFIDh/Ssb7Gp2HN/9xnCqPSid0Qc/ZlrY8PxpUwVZASy38NV1F1OeenVolhkeoOIFpvoT+52rUUuaisxdMuBJqDtS2xPHp0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
