travis:
  secure:
    BINSTAR_TOKEN: mK95oEh37WM2QKzdNrMOZmzaccyBVyxt3pfDHXyeVaTmpfj3T8MP/Ws3fAweYrHKra/A5ZH+NdfHpjYg05OMCpHUtOa8/udZnidyKadRmFjCDEI7C+H2MsmFgdLUiEQiHXBcPvLc2co8Zkg9Hnhpk4Q9t+pmJeNENZzAELgDKmm0lbIjahHtQuDFKFLkuDjmWqdPKMlwqkbNtUjhAHgeItfHiCGK0+I11ItwpHGbIUnk4aW3mJGBOrHWP3utVzpYtMp+AyMsbHZEFEJD/GyO+QCCWcsaTCr4aN8FomxhvcSFoaZMFPH1DrMC0l1R1E13MiEVrcyT5A2C4RG68OaAQonrYV7HXQRI7JsJ81YmKSn7EDYvmCfzRyb1jOMPn2ytAdAguklNjzgP/0SqqoL4S3suFGvmOcwx2lKzRT0Tpyx98wr7/4hE1M512PaT8ac5K4Po7jWTXbChkwno/xJooTy+5IrsMw41INxix8tuA4u8vRTJkrEum/LM8RLqA49vxzJLPBgfOnatcjZ/jdgXgIB0vzzx4jRbCT9SKYgm70OYLipHUd9v467bE9WG10tBo8zQnoIkMzBK8MuFGKe2ZeJnqEm+9DLxwMXmK5avCZ8iPSXPc4DLV/sU3vb6iNBNnHFyqBdxtgwkjg7z9M8VpZD1imwtz8FLOPYGFf+xzbA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
